### ISSUE TITLE
Usage with key-value pair state tools like Zustand

### ISSUE THREAD

**Issue by netgfx** [julienetie/db64#20]
Could this work with Zustand https://github.com/pmndrs/zustand/blob/main/docs/integrations/persisting-store-data.md#how-can-i-use-a-custom-storage-engine

I see that this library needs initialization so it will probably need some middleware function in order to create the store and then expose the get, set functions in order for Zustand to use them right?

**Comment by julienetie** [comment]
Hey Michael, 

Thanks for reaching out. I recently had surgery, I should be able to take a look early in the coming week.

**Comment by julienetie** [comment]
You're correct. It will need a method to create a DB with stores. 
The other concern would be to manage or expose errors, as well as deleting and re-creating a DB if needed.

I'm going to close this issue, but please open another if you come across any problems.
